### ISSUE TITLE
Move content to docs repo, slim down, change theme

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-framework.github.io#36]

**Comment by hauten** [comment]
- [ ] Update theme to Cayman like on https://github.com/spack/legacy-spack.io
- [ ] Main menu: GitHub repo, Docs, Papers/Pubs, Release notes (instead of News)
- [ ] Update intro/explanatory text (see current welcome text under Doc)
- [ ] Move contrib & quick start content to docs
- [ ] Build prereq content - also move to docs? http://flux-framework.org/docs/requirements/
Related to https://github.com/flux-framework/docs/issues/1

**Comment by hauten** [comment]
@SteVwonder @gonsie and/or anyone from the Flux team, when you have time to review: 

I created a separate repo to play around with the Cayman theme. I copied over the news posts, renamed them as Releases, and changed some of their metadata in order to get, for instance, the download link on Releases. What do you think? What would you like to see changed?
https://github.com/hauten/flux-sandbox
https://hauten.github.io/flux-sandbox/

Outstanding issues:
1. Meg gave me the new Flux logo, which I haven't added yet.
2. I didn't copy over PDFs to link from Publications.
3. I'm having trouble with site.baseurl. It's fine on Publications & Releases, but when you click on a release to view a _post (e.g., https://hauten.github.io/release/2019/12/06/flux-sched-v0.8.0.html), it "forgets" /flux-sandbox/ in the URL and therefore breaks. This was breaking elsewhere too, so for now I've pasted in the URL in _config.yml where ideally {{ site.baseurl }} should go. I need help fixing this.

**Comment by SteVwonder** [comment]
> What do you think?

Wow! I think it looks freaking awesome!

> What would you like to see changed?

A few minor requests:

- Can you drop flux-capacitor from the main list of projects?  Unfortunately its a few years out of date.  We may update it at some point, but it has bit rotted quite a bit at this point.
- Can the "Latest Release" on the homepage become "Latest Releases" and show the latest release of both flux-core and flux-sched?
- Can you switch the contact email address to `flux-discuss@lists.llnl.gov`?  The internal one is locked down.

Thanks!

> I'm having trouble with site.baseurl.

Just a guess, but does the entry in _config.yml need to be updated to be "/flux-sandbox"? https://github.com/hauten/flux-sandbox/blob/57f91c4ba7bbb6549dd8cdacc37d139df1e875ba/_config.yml#L10

**Comment by grondo** [comment]
Thanks for taking this on. Looks great!

> What would you like to see changed?

We'll probably want to expand the short blurb on the main page describing Flux (it was originally written long ago), and modify it slightly to more accurately describe current Flux (e.g. I don't think we call it *The* Flux Framework anymore, though I could be wrong). However, for now I assume you probably wanted comments more about the general layout and design. These are all really minor questions/suggestions:

 * You probably already planned to take care of this after grabbing the new logo, but the main background color seems slightly off. Personal preference is a dark theme as in the original site, but I'm not a designer and I'm fine with anything that fits the color scheme of the logo.
 * Instead of `Releases` at the bottom, could we a more general "News" or "Recent posts" with the latest news post at the top? Mostly these will be release posts anyway.
 * Shorten "Documentation" to "Docs" ?
 * Somewhere on the front page we should have a "Getting started" link directly to the Quickstart guide, maybe this could be in the text describing Flux? :man_shrugging: 
 * This might just be on my laptop, but the logo+header/navigation is so large that it isn't immediately apparent that there is anything to read below. Also if you go to links within the site, the page doesn't change at all. Perhaps the header could be scaled down, or maybe when you navigate away from "Home" the large title and subtitle go away and you just have the Flux logo and navigation buttons? (like on the current site)

Really nice how this is turning out and the help is appreciated!!

**Comment by hauten** [comment]
Thx @grondo & @SteVwonder, very helpful! I'll work on this and get back to you.

**Comment by hauten** [comment]
- [x] Drop flux-capacitor from the main list of projects
- [x] Change "Latest Release" on the homepage to "Latest Releases"
Instead of Releases at the bottom, could we a more general "News" or "Recent posts" with the latest news post at the top? Mostly these will be release posts anyway. (this contradicts the previous item; leaving it as Latest Releases for now)
- [ ] Show the latest release of both flux-core and flux-sched
- [x] Switch the contact email address to flux-discuss@lists.llnl.gov
- [x] Expand the short blurb on the main page describing Flux & modify it slightly to more accurately describe current Flux (don't call it The Flux Framework anymore)
- [ ] Add new logo
- [ ] Main background color seems slightly off; can it be darker as long as it fits the logo
- [x] Shorten "Documentation" to "Docs"
- [x] Somewhere on the front page we should have a "Getting started" link directly to the Quickstart guide, maybe this could be in the text describing Flux
- [ ] Logo+header/navigation is too large - perhaps the header could be scaled down, or maybe when you navigate away from "Home" the large title and subtitle go away and you just have the Flux logo and navigation buttons? (like on the current site)
- [ ] If you go to links within the site, the page doesn't change at all (baseurl problem)
- [x] Update entry in _config.yml to "/flux-sandbox"

**Comment by hauten** [comment]
Team - I believe I've gotten as far as my skill set will take me. I have one remaining task above (move Build Prereq content to docs repo) before I close this issue. All outstanding items related to the new theme are now in issue #39.

**Comment by hauten** [comment]
I'll close this after https://github.com/flux-framework/flux-docs/pull/31 is successfully merged.

**Comment by SteVwonder** [comment]
Thanks @hauten!  If you add `Closes: #36` to the bottom of the original post/comment in #31, then GitHub will automatically close this issue when #31 is merged.
